### ISSUE TITLE
Machine Birthing System

### ISSUE THREAD

**Issue by markrey** [Symantec/Dominator#277]
Hi Everyone,

I am going through various documents for Dominator.
I saw Machine Birthing system document which reads PXE boot requests.
https://docs.google.com/document/u/1/d/1y7rPTuG145fdPhqaCdLu_03D1dC1UTRzyEq61ygIQeg/pub

Would it be possible to share link to the Machine Birthing system source?

Thanks,
Mark

**Comment by rgooch** [comment]
The Birther has not been implemented. We deployed Ironic in the interim and that has satisfied our needs for the time being.

**Comment by rgooch** [comment]
https://wiki.openstack.org/wiki/Ironic
