### ISSUE TITLE
Docker or Vagrant or VM Build

### ISSUE THREAD

**Issue by markrey** [Symantec/Dominator#278]
Hi Everyone,

I wanted to check if combination various tools ( server side - dominator, image server etc. ) are available as ready to deploy format.

Either Docker Compose or Vagrant or others would do.

https://github.com/Symantec/Dominator/tree/master/init.d

If not, i can make and contribute.

Thanks
Mark

**Comment by rgooch** [comment]
No, the only packaging work that has been done is to build a tarfile for installing `subd`. I'm not sure how much value there is to putting the components inside containers, since **Dominator** is envisioned to lay down the foundations for running a container farm, for example.
