### ISSUE TITLE
cmd/dominator: fails to 'go get' on raspberry pi

### ISSUE THREAD

**Issue by masiulaniec** [Symantec/Dominator#355]
```
pi$ go install ./cmd/dominator
# github.com/Symantec/Dominator/lib/wsyscall
lib/wsyscall/wrappers_linux.go:11: cannot use source.Nlink (type uint32) as type uint64 in assignment
lib/wsyscall/wrappers_linux.go:17: cannot use source.Blksize (type int32) as type int64 in assignment
# github.com/Symantec/Dominator/lib/filesystem
lib/filesystem/compare.go:192: cannot use left.MtimeSeconds (type int64) as type int32 in assignment
lib/filesystem/compare.go:193: cannot use int64(left.MtimeNanoSeconds) (type int64) as type int32 in assignment
lib/filesystem/compare.go:194: cannot use right.MtimeSeconds (type int64) as type int32 in assignment
lib/filesystem/compare.go:195: cannot use int64(right.MtimeNanoSeconds) (type int64) as type int32 in assignment
lib/filesystem/compare.go:361: cannot use left.MtimeSeconds (type int64) as type int32 in assignment
lib/filesystem/compare.go:362: cannot use int64(left.MtimeNanoSeconds) (type int64) as type int32 in assignment
lib/filesystem/compare.go:363: cannot use right.MtimeSeconds (type int64) as type int32 in assignment
lib/filesystem/compare.go:364: cannot use int64(right.MtimeNanoSeconds) (type int64) as type int32 in assignment
pi$
```

**Comment by rgooch** [comment]
I have pushed two commits to my fork: https://github.com/rgooch/Dominator
Please verify if these solve the problems for you and then I'll push upstream.

**Comment by masiulaniec** [comment]
I lost access to that pi but I was able to test the fix using the built-in cross-compiler:

```
$ GOOS=linux GOARCH=arm GOARM=6 go install github.com/rgooch/Dominator/lib/filesystem
$ GOOS=linux GOARCH=arm GOARM=6 go install github.com/rgooch/Dominator/lib/wsyscall
$
```

**Comment by rgooch** [comment]
Thanks. Fix merged.
BTW: What are you using it for? I always envisaged **Dominator** to be used on a fleet of ... bigger machines.

**Comment by masiulaniec** [comment]
Right now I was mainly using it to test speed of compilation of my new pi (I'm new to this category of hardware).

But apart from that, I find Dominator's decision to reduce the problem of system configuration to the problem of managing just two entities, files and services, to be refreshingly simple. I wonder if such approach could replace more complex systems such as Puppet and Chef. I realize it would make Dominator relatively harder to deploy in comparison to these two because the underlying operating systems are generally not ready for this radical simplicity. I might use the pi to create an experimental "distro" that is geared towards Dominator-based config management.

**Comment by rgooch** [comment]
Yes, **Dominator** is definitely intended to replace Puppet, Chef, Ansible and other systems that "fry" machines rather than "bake" them. It's inspired by the system used at a very large Internet company to mange it's fleet, and the problems we experienced with Puppet-based system maintenance.

The underlying distributions don't have problems with this approach (for cleanliness you just delete some no-longer-needed cron jobs). The work is in changing your approach from the "fry" model to the "bake" model. The "bake" model is what Spinnaker uses to manage the full CI/CD workflow for stateless systems, and **Dominator** extends that to stateful systems.

Building images for **Dominator** will soon be even easier with the soon-to-be-released `Imaginator` which is a high performance custom image builder.

**Comment by rgooch** [comment]
FYI: `Imaginator` has been implemented. You can start using it if you want. It's not yet documented, but we are using it in production. We've migrated several image streams over to it and are wrapping up the remaining ones. After that I'll write some documentation. It takes ~1m15s to build a "minimal" image and ~45s to build a "base" image on top of the "minimal" image. Typical application images take under 30s to build. There is room for optimisation.

There's an old design document about image life-cycle management which has a bit more information about the image builder: https://docs.google.com/document/d/e/2PACX-1vQC_T691_Xx8YXWz7DjhigL5iqDKHSzhq4DHgXe6wDpEW5wwgacYhCRzsG_k4Ge33FI9qfVOUBOpU2m/pub
