### ISSUE TITLE
make-cert utility is not available

### ISSUE THREAD

**Issue by zaletniy** [Symantec/Dominator#361]
Looks like make-cert utility is not there anymore, however it is mentioned in [getting-started.md ](https://github.com/Symantec/Dominator/blob/master/user-guide/getting-started.md) guide

What is new recommended way to generate certificates for subd?
Thank you

**Comment by rgooch** [comment]
When I go to the guide, I see a (working) link to the `make-cert` utility. It's still the recommended way to generate certificates. Can you double check?

**Comment by zaletniy** [comment]
Yeap, it is there. Was looking at $GOPATH/bin directory.
Thank you
