### ISSUE TITLE
Documentation: Initial subd<->dominator relation establishing

### ISSUE THREAD

**Issue by zaletniy** [Symantec/Dominator#362]
I was not able to find the description of the process of registration of new VM started with subd on board in Dominator or/and mdb.
Who initiates this relation initially? VM with subd or dominator calling subd?
What is recommended and possible ways?

The only mention I have found is discovering inventory via cis [here](https://github.com/Symantec/Dominator/tree/master/cmd/mdbd#configuration-files)
Any other sources are supported now?

Also, could you please point me to some samples of config files if there are any?

Very appreciate any clarifications.

**Comment by rgooch** [comment]
You don't really "register" subs with the dominator. Instead, they are _discovered_ by the dominator, using `mdbd`. `mdbd` has support for a number of "drivers", including directly querying AWS. One of the drivers is `aws-local` which will find all instances in the region (for all the accounts in your `~/.aws/credentials` file). Just put `aws-local` in your `/var/lib/Dominator/mdb.sources.list` file.

Does that help?

**Comment by rgooch** [comment]
I've updated the documentation. Please take a look and comment or resolve.

**Comment by zaletniy** [comment]
Yes, new code and source code reference help a lot.
