### ISSUE TITLE
Example manifest files? 

### ISSUE THREAD

**Issue by cholcombe973** [Symantec/Dominator#594]
I'm working my way through the docs here.  I'm wondering if there are any example manifest files I can reference.  Thanks!

**Comment by rgooch** [comment]
I've just checked in the first example in PR# 602. This is a (very lightly) scrubbed version of the manifest we use internally. See: https://github.com/Symantec/Dominator/tree/master/cmd/imaginator/example-manifests/dominator
I will check in more examples (imageserver, imaginator, image-unpacker, hypervisor, fleet-manager) as I scrub them to remove any private information.
Please let me know if this is helpful.

**Comment by rgooch** [comment]
I've added: https://github.com/Symantec/Dominator/tree/master/cmd/imaginator/example-manifests/imageserver
