### ISSUE TITLE
Install scripts or packages

### ISSUE THREAD

**Issue by cholcombe973** [Symantec/Dominator#595]
I think some/most of the pieces are here in the repo but an install package or script would really be helpful.  I see there's an install.lib file under scripts that might be what I want but I'm not sure how to use it.

**Comment by rgooch** [comment]
There are Makefile targets to create tarfiles for the different daemons. Those tarballs contain an `install` script that you can run. The `install` scripts support CentOS/RedHat and Debian/Ubuntu.
Does that help?

**Comment by cholcombe973** [comment]
Yeah that'll work.  Thanks!
