### ISSUE TITLE
RPC Protocols

### ISSUE THREAD

**Issue by cholcombe973** [Symantec/Dominator#599]
Would you consider using a different rpc protocol such as protobuf, thrift, etc so that components can be subbed into dominator that are written in another programming language?  It looks like the existing code uses srpc if I'm reading the code correctly which seems to be a golang specific rpc mechanism.  I'd like to implement a filegen-server but learning Go presents a roadblock for me and greatly extends the time it'll take for me to implement something useful.

**Comment by rgooch** [comment]
I might consider supporting additional protocols, but not a replacement (i.e. dropping existing support).
For the topic of supporting other languages (or, really, non-GOB encoding formats), something I've had on the back-burner is adding support for alternate encoders (i.e. JSON). In fact, if you look at https://godoc.org/github.com/Symantec/Dominator/lib/srpc#RegisterName you can see that I've laid some of the groundwork for this already: applications can register SRPC methods which done care which encoding is used. It would be quite simple to add another HTTP handler for JSON encoding. Adding client support for different encodings should also be doable. This would be much faster than adding support for a whole new RPC library.

**Comment by cholcombe973** [comment]
Yeah supporting additional protocols sounds great!  HTTP or otherwise is fine although I think I'd prefer HTTP for ease and SSL encryption.  The only reason I mentioned protobuf or thrift is because I can build a library using whatever protocol/git release tag you define and I can be certain it'll work.  JSON is easily modified and broken.  There's no guaranteed compatibility.  That said it is very popular these days and I wouldn't blame you for using it :).  
I actually found a GOB encoding library in rust that I can use.  However I don't understand the back and forth just yet.

**Comment by rgooch** [comment]
The underlying protocol is HTTP. The client then does a CONNECT for an SRPC enpoint and then the TLS handshake is done. After that the client sends a string with the method name and the server sends a response indicating whether access is permitted or not. From then on, it depends on the method being called on whether it's an encoded (GOB or whatever) request/response or something more complicated like a streaming protocol. Even with the streaming methods, it's either a sequence of (GOB) encoded messages or raw data. Swapping out GOB for JSON and implementing in another language should be fairly straightforward.

**Comment by rgooch** [comment]
Update: I'm doing some refactoring so that it will be easier for both client and servers to use a different encoding. For Go-based servers, I'll add a handler for JSON encoding, so those will handle both encodings pretty transparently (most servers will just work without further changes).
For Go-based clients calling servers which don't support GOB encoding, my plan is to change the client library to first try the GOB URL and if that doesn't work to try the JSON URL. So, again, this will be mostly transparent for Go clients.

**Comment by cholcombe973** [comment]
Yeah that sounds great!

**Comment by rgooch** [comment]
@cholcombe973: I've just merged PR #609 which adds JSON endpoints. SRPC servers using the lib/srpc package will support JSON and clients using this package will automatically try JSON coders if the GOB coder is missing (allowing a Go client to call a non-Go server). I've also documented the protocol in the package documentation.
Closing issue, as this should provide you what you need.
