### ISSUE TITLE
Community Site

### ISSUE THREAD

**Issue by cholcombe973** [Symantec/Dominator#600]
Is there a gitter/slack/irc/etc place where I can chat with fellow dominator users?  I'm running into some silly n00b issues that I think could get resolved really easily but would take forever to do over github issues and poking around the source code.

**Comment by rgooch** [comment]
https://join.slack.com/t/cloud-foundations/shared_invite/enQtNjA5NzI1MDI1NjUyLTZlYWI4ZWQ1MGUzMWUyZTQyNTA0MTU4YTRjMGQ0OWE2MzYyMTFkMDgxYWMxNmI1YjFmOGYwOTIyNzZlMDU1YmU
