### ISSUE TITLE
Exporting VMs to libvirt

### ISSUE THREAD

**Issue by rgooch** [Symantec/Dominator#614]
@cviecco my current thinking is to have a similar workflow as when importing libvirt VMs: stop the SmallStack VM, create libvirt VM, ask to commit, defer or abandon.
Commit: destroy the SmallStack VM.
Defer: leave both VMs existing, SmallStack VM is stopped. Manual cleanup essential.
Abandon: destroy libvirt VM, start SmallStack VM.

Sound good?

**Comment by cviecco** [comment]
There is also a step needed to export the dhcp options so that they can be added to the operators dhcp infrastructure

**Comment by rgooch** [comment]
@cviecco: rather than a special tool to export to libvirt, we could instead have a more generic tool that exports the VM metadata information (which includes the IP and MAC addresses) in JSON format, piped to a user-provided script. The script would import the VM into whichever system you want. The generic tool would control the workflow, including the commit/defer/abandon query and actions.

**Comment by cviecco** [comment]
I dont see it generic until I understand more targets. Besides libvirt support, also openstack? this could works but I would prefer a non-generic tool first and making it more generic  once we understand more output targets.

**Comment by rgooch** [comment]
@cviecco I have just merged PR# 616 which implements the ability to export a SmallStack VM to either a generic tool or to libvirt/virsh. You can find the instructions on how to export to virsh here: https://github.com/Symantec/Dominator/blob/master/cmd/vm-control/README.md

I think this should resolve this issue. Please reopen if this is not what you had in mind.
